[book]
authors = ["Jho00"]
language = "en"
multilingual = false
src = "src"
title = "system-engineering-playbook"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []
